config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "categories" => "categories#index"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "category_lessons" => "lessons#show"

  resources :users
  resources :lessons
  resources :categories
  resources :words
  resources :relationships
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_activities = Activity.feed_all(current_user.following_ids,
        current_user).recent.paginate page: params[:page],
        per_page: Settings.paginate_per_page
    end
  end

  def help
  end
end

app/views/static_pages/help.html.erb
<h1><%= t "static_pages.help.help" %> : <%= t "static_pages.help.email" %></h1>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row" >
    <aside class="col-md-4" >
      <%= render "shared/user_infor" %>
    </aside>
    <div class="col-md-8" >
      <%= link_to t("static_pages.home.word"), words_path, class: "btn btn-lg btn-primary" %>
      <%= link_to t("static_pages.home.lesson"), categories_path,
        class: "btn btn-lg btn-primary" %>
    </div>
    <div class="row" >
      <div class="col-md-9 col-md-offset-3" >
        <%= render "shared/feed" %>
      </div>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "static_pages.home.welcome" %></h1>
    <%= link_to t("static_page.home.sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>