config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "categories" => "categories#index"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "category_lessons" => "lessons#show"

  resources :users
  resources :lessons
  resources :categories
  resources :words
  resources :relationships
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :lesson_words
  has_many :results

  validates :name , presence:true

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc{|a| a["content"].blank?}

  scope :all_word, ->user_id{}
  scope :learned, ->user_id{where("id in (select word_id from lesson_words where
    lesson_id in (select id from lessons where user_id = #{user_id}))")}
  scope :no_learn, ->user_id{where("id not in (select word_id from lesson_words where
    lesson_id in (select id from lessons where user_id = #{user_id}))")}
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController

  before_action :logged_in_user
  before_action :load_word, only: [:edit, :destroy, :update]

  def index
    @words = Word.paginate(page: params[:page],per_page: Settings.page_per).order :name
  end

  def new
    @word = Word.new
    @categories = Category.all
    Settings.number_answers.times do
      @answer = @word.answers.build
    end
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "words.create_success"
      redirect_to admin_words_path
    else
      flash[:error] = t "words.create_fails"
      redirect_to :back
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "flash.delete"
      redirect_to admin_words_path
    else
      flash[:success] = t "words.delete_fails"
      redirect_to admin_words_path
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "flash.update"
      redirect_to admin_words_path
    else
      flash[:error] = t "words.update_fails"
      render :edit
    end
  end

  private

  def word_params
    params.require(:word).permit :name, :category_id, answers_attributes: [:id,
      :content, :is_correct, :_destroy]
  end

  def load_word
    @word = Word.find params[:id]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    if !params[:category_id].nil? && params[:category_id].empty?
      @words = Word.send params[:option], current_user.id
    elsif category = @categories.detect{|category| category.id == params[:category_id].to_i}
      @words = category.words.send params[:option], current_user.id
    else
      @words = []
    end
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
  def add_child_button name, association, target
    content_tag(:spam, "<span class='btn btn-success'>#{name}</span>".html_safe,
      class: "add_child", "data-association"=> association, target: target)
  end

  def new_fields_template f, association
    new_object = f.object.class.reflect_on_association(association).klass.new
    tmpl = f.fields_for(association, new_object,
      child_index: "new_#{association}") do |b|
      render(partial: association.to_s.singularize + "_form", locals: {f: b})
    end
    tmpl = tmpl.gsub /(?<!\n)\n(?!\n)/, " "
    return "<script> var #{association.to_s}_form = '#{tmpl.to_s}' </script>"
      .html_safe
  end
end

app/views/admin/words/_answer_form.html.erb
<div class="row answer-form">
  <div class="col-md-5 ">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control content-answer" %>
    </div>
  <div class="col-md-3">
    <%= f.label :is_correct, class: "checkbox-inline" %>
    <%= f.check_box :is_correct, class: "checkbox" %>
  </div>
  <%= f.hidden_field :_destroy, class: "removable" %>
  <div class="col-md-2">
    <%= f.button :remove, class: "glyphicon glyphicon-remove remove_fields" %>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>

  <span class="alert_error" style="visibility: hidden" ><%= t "alert_error" %></span>
  <br>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control"%>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id, options_for_select(@categories.map{|c| [c.name,
      c.id]}, selected_key = f.object.category_id), {}, class: "form-control" %>
  </div>
  <div id="answers">
    <%= f.fields_for :answers do |answer_form| %>
      <%= render "shared/error_messages", object: answer_form.object %>
      <%= render "answer_form", f: answer_form  %>
    <% end %>
  </div>
  <div class="add-answer">
    <%= add_child_button t("add_answer"), :answers, "#answers" %>
    <%= new_fields_template f, :answers %>
  </div>

  <%= f.submit t("button"), class: " submit-word btn btn-primary pull-right" %>
<% end %>

app/views/admin/words/edit.html.erb
<% provide :title, t("words.edit") %>
<div class="row">
  <div class="col-md-7 col-md-offset-2 ">
    <div class="panel panel-primary">
      <div class="panel-heading"><h2><%= t "words.edit" %></h2></div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("word") %>
<div>
  <div class="row">
    <div class="col-md=8">
      <%= link_to t("new_word"), new_admin_word_path , class: "btn btn-primary" %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t "word" %></th>
            <th><%= t "category" %></th>
            <th><%= t "mean_correct" %></th>
            <th><%= t "tool" %></th>
          </tr>
        </thead>
        <tbody>
          <% @words.each do |word| %>
            <tr id="word-<%= word.id %>">
              <td><%= word.name %></td>
              <td><%= word.category.name %></td>
              <td>
                <% word.answers.each do |answer| %>
                  <%= answer.content if answer.is_correct %>
                <% end %>
              </td>
              </td>
              <td>
                <%= link_to t("words.edit"), edit_admin_word_path(word) %>
                <%= link_to t("words.delete"), admin_word_path(word), method: :delete,
                  data: {confirm: t("words.confirm")}, class: "delete_category" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @words %>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t("words.new_word") %>
<div class="row">
  <div class="col-md-7 col-md-offset-2 ">
    <div class="panel panel-primary">
      <div class="panel-heading"><h2><%= t "words.new_word" %></h2></div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>