config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "categories" => "categories#index"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "category_lessons" => "lessons#show"

  resources :users
  resources :lessons
  resources :categories
  resources :words
  resources :relationships
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "flash.shared_error.the_form" %> <%= pluralize object.errors.count, t("flash.shared_error.e") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_activities.any? %>
  <ol id ="activity" >
    <%= render @feed_activities %>
  </ol>
  <%= will_paginate @feed_activities %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= relationships_path id: @user.id, type: "following" %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <strong>
      <%= t "users.show.following" %>
    </strong>
  </a>
  <a href="<%= relationships_path id: @user.id, type: "followers" %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <strong>
      <%= t "users.show.followers" %>
    </strong>
  </a>
</div>

app/views/shared/_user_infor.html.erb
<h2><%= current_user.name %></h2>
<span><%= link_to t("users.infor"), current_user %></span>