config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "categories" => "categories#index"
  get "help" => "static_pages#help"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  get "category_lessons" => "lessons#show"

  resources :users
  resources :lessons
  resources :categories
  resources :words
  resources :relationships
  resources :categories, only: [:index, :show] do
    resources :lessons
  end
  namespace :admin do
    root "categories#index"
    resources :categories
    resources :words
    resources :users
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy
  accepts_nested_attributes_for :words, :lessons

  validates :name, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
  validates :description, presence:true, length: {maximum: 100},
    uniqueness: {case_sensitive: false}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :logged_in_user
  before_action :load_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.create_success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t "flash.delete"
    redirect_to admin_categories_path
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.update"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit t("button"), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t("categories.edit.edit_category") %>
<h1><%= t "categories.edit.edit_category" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% if logged_in? %>
  <div class="row" >
    <%= link_to t("category.new.new_category"), new_admin_category_path, class:
      "btn btn-primary" %>
    <div class="col-md=8">
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= t "category" %></th>
            <th><%= t "desciption" %></th>
            <th><%= t "tool" %></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.description %></td>
              <td>
                <div class="manage_category">
                  <%= link_to t("categories.edit.edit"), edit_admin_category_path(category) %>
                  <%= link_to t("categories.destroy.delete"), admin_category_path(category),
                    method: :delete, data: {confirm: t("categories.destroy.confirm")},
                    class: "delete_category" %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/admin/categories/new.html.erb
<% provide :title, t("categories.new.new_category") %>
<h1><%= t "categories.new.new_category" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>